config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources:posts do resources:coments
  end
  root"posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :coments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :posts 
  has_many :coments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
    before_action :find_post
    before_action :find_coment, only: [:edit, :update,:destroy]
    before_action :authenticate_user!

    def create

        @coment= @post.coments.create(coment_params)
        @coment.user_id = current_user.id

        if@coment.save
            redirect_to post_path(@post)
        else 
            render 'new'
        end
    end    
    def edit
        @coment = @post.coments.find(params[:id])
    end    

    def update
        if @coment.update(coment_params)
            redirect_to post_path(@post)
        else
            render 'edit'
        end        
    end    

    def destroy 
        @coment.destroy
        redirect_to post_path(@post)
    end    

    private

        def coment_params
            params.require(:coment).permit(:content)
        end 
        def find_post
            @post = Post.find(params[:post_id])
        end
        def find_coment
            @coment = @post.coments.find(params[:id])
        end
end    

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :find_post, only:[:show,:edit,:update,:destroy]
    before_action :authenticate_user!, except:[:index,:show]

    def index
        @posts = Post.all.order("created_at DESC")
    end 

    def show 
        
    end 

    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update
        @post.category_id = params[:category_id]
        if @post.update(post_params)
            redirect_to post_path
        else    
            render 'edit'
        end    
    end

    def destroy
        @post.destroy
        redirect_to root_path
    end  

    def create
        @post = current_user.posts.build(post_params)
        @categories = Category.all.map{ |c| [c.name, c.id] }
        if @post.save
            redirect_to root_path
        else
            render 'new'
        end       
    end

    def  new
        @post = current_user.posts.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end    
    private
        def post_params
            params.require(:post).permit(:title,:message,:category_id)
        end    
        def find_post
            @post = Post.find(params[:id])
        end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/coments/_coment.html.erb
<p><%= coment.content%></p>
<p>Criado por: <%=coment.user.email%></p>


<%if user_signed_in? %>
    <%if coment.user_id == current_user.id%>
    <%=link_to "Editar", edit_post_coment_path(coment.post, coment)%>
    <%=link_to "Excluir", post_coment_path(coment.post,coment), method: :delete,data:{confirm: "Certeza?"}%>   
    <%end%>
<%end%>    

app/views/coments/_form.html.erb
<%= simple_form_for([@post,@post.coments.build]) do |f| %>
    <%=f.input  :content ,label: "Comente:"%>
    <%=f.button :submit%>
<% end %>   

app/views/coments/edit.html.erb
<h1>Edição</h1>
<%= simple_form_for([@post,@coment]) do |f| %>
<%= f.input :content, label: "Comentario"%>
<%= f.button :submit%>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <div class="navbar navbar-default">
          <div class="container">
              <div class="navbar~header">
                  <%=link_to "Pagina inicial",root_path, class:"navbar-brand" %>
              </div>
              <ul class="nav navbar-nav">
                  <li><%=link_to "Sign In", new_user_registration_path %></li>
                  <%if user_signed_in?%>
                    <li><%=  link_to "Sign Out", destroy_user_session_path,method: :delete%></li>
                  <%else%>
                    <li><%= link_to "Log In",new_user_session_path %></li>
                  <%end%>
              </ul>
              <% if user_signed_in? %> 
                  <p><%= link_to "Novo post", new_post_path, class: "navbar-right navbar-text navbar-link" %></p>
              <%end%>    
          </div>
      </div>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title,label:"Titulo do post" %>
  <%= f.input :message,label:"Mensagem" %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edição </h1>

<%= simple_form_for @post do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title,label:"Titulo do post" %>
  <%= f.input :message,label:"Mensagem" %>
  <%= f.button :submit %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <%= link_to "Visualizar",post_path(post),class:"btn btn-default"%>
<%end%>

app/views/posts/new.html.erb
<h1> Novo Post</h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h5>Categoria: <%=@post.category.name%></h5>
<p>Criado por: <%=@post.user.email%></p>
<h2><%= @post.message %></h2>

 

<h5>Comentarios:</h5>
<%= render @post.coments%>  

<h3></h3>
<%=render 'coments/form'%>

<%= link_to "Voltar", root_path,class:"btn btn-default"%>
<%if user_signed_in?%>
    <%if @post.user_id == current_user.id %>
        <%= link_to "Editar Post", edit_post_path(@post),class:"btn btn-default"%>
        <%= link_to "Deletar",post_path(@post),method: :delete, data:{confirm:"Certeza?"},class:"btn btn-default"%>
    <%end%>    
<%end%>    